ALTER TABLE banks ADD COLUMN department TEXT DEFAULT NULL;
ALTER TABLE banks ADD COLUMN address_line_1 TEXT DEFAULT NULL;
ALTER TABLE banks ADD COLUMN address_line_2 TEXT DEFAULT NULL;
ALTER TABLE banks ADD COLUMN contact_email TEXT DEFAULT NULL;
