import json
from pathlib import Path

def run(project_root: Path):
    """
    Simple CSS bloat detector: flags files over size/line thresholds.
    Uses .bgl_core/brain/css_inventory.json generated by inventory step.
    """
    inv = project_root / ".bgl_core" / "brain" / "css_inventory.json"
    if not inv.exists():
        return {"passed": False, "evidence": ["css_inventory.json not found"], "scope": ["css"]}

    data = json.loads(inv.read_text(encoding="utf-8"))
    findings = []
    for f in data:
        if f.get("bytes", 0) > 50_000 or f.get("lines", 0) > 1500:
            findings.append(f"{f['path']} size={f['bytes']} bytes lines={f['lines']}")

    passed = len(findings) == 0
    return {
        "passed": passed,
        "evidence": findings if findings else ["All CSS files below thresholds"],
        "scope": ["css"],
    }

if __name__ == "__main__":
    print(run(Path('.')))
