import json
from pathlib import Path


def run(project_root: Path):
    """
    JS bloat detector: flags large/long files and reports top offenders.
    Uses .bgl_core/brain/js_inventory.json generated by inventory step.
    """
    inv = project_root / ".bgl_core" / "brain" / "js_inventory.json"
    if not inv.exists():
        return {"passed": False, "evidence": ["js_inventory.json not found"], "scope": ["js"]}

    data = json.loads(inv.read_text(encoding="utf-8"))
    findings = []
    WARN_BYTES = 30_000
    FAIL_BYTES = 50_000
    WARN_LINES = 900
    FAIL_LINES = 1_500

    for f in data:
        size = f.get("bytes", 0)
        lines = f.get("lines", 0)
        if size >= FAIL_BYTES or lines >= FAIL_LINES:
            findings.append(f"FAIL {f['path']} size={size}B lines={lines}")
        elif size >= WARN_BYTES or lines >= WARN_LINES:
            findings.append(f"WARN {f['path']} size={size}B lines={lines}")

    passed = all(not item.startswith("FAIL") for item in findings)
    if not findings:
        findings = ["All JS files below thresholds"]
    else:
        findings = sorted(findings, reverse=True)

    return {
        "passed": passed,
        "evidence": findings,
        "scope": ["js"],
    }


if __name__ == "__main__":
    print(run(Path('.')))
